# **Lab Assignment 2**
<p> Name: Maharaj Hossain Tanim <br> ID: 2215151040 <br> Section: 7(A2) Course: Simulation and Modeling Lab <br> Course Code: CSE 413</p>


In [19]:
# importing necessary libraries

import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
# With fixed seed
np.random.seed(10)
seeded_matrix = np.random.randint(1, 51, (3, 3))
print("Matrix with fixed seed:\n", seeded_matrix)

# Without fixed seed
np.random.seed(None)
non_seeded_matrix = np.random.randint(1, 51, (3, 3))
print("\nMatrix without fixed seed:\n", non_seeded_matrix)

Matrix with fixed seed:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Matrix without fixed seed:
 [[44 13 31]
 [30 49 47]
 [11 42  4]]


# **Differences between Seeded and Non-seeded outputs**
---
<p>-> In first matrix "np.random.seed(10)" ensures that the random numbers that was generated first time will remain same each time the code runs. <br> ->In the second matrix "np.random.seed(None)" is opposite of the previous matrix. It generates randam value each time the code runs.<br> -> Why seed value 10? answer for that is any integer can be used as seed. It just ensure the same random sequance when used. Different seed values will produce different sequences of random numbers.</p>



---


